db.sevilla.insertMany([
    {id: 1,
    Municipio: "Carmona",
    Estacion: "Carmona",
    Altitud_Metros: 50,
    Latitud: "Norte",
    Grado_La: 37, 
    Minuto_La: 33, 
    Segundo_La: 56, 
    Longitudo: "Oeste", 
    Grado_Lo: 5, 
    Minuto_Lo: 44, 
    Segundo_Lo: 26, 
    Predicción: "Lluvia",
    Probabilidad_En_TantoPorciento: 100, 
    TemperaturaMinima: 12,
    TemperaturaMaxima: 16,
    UltimaActualización: "22-11-2020",
    FechaPredicción: "25-11-2020"
}, 
    {id: 2, Municipio: "Carrión de los Céspedes", Estacion: "Carrión de los Céspedes", Altitud_Metros: 76, Latitud: "Norte", Grado_La: 37,  Minuto_La: 21,  Segundo_La: 36,  Longitudo: "Oeste",  Grado_Lo: 5,  Minuto_Lo: 20,  Segundo_Lo: 3,  Predicción: "Lluvia", Probabilidad_En_TantoPorciento: 100,  TemperaturaMinima: 10, TemperaturaMaxima: 17, UltimaActualización: "22-11-2020", FechaPredicción: "25-11-2020"},
    {id: 3, Municipio: "Cazalla de la Sierra", Estacion: "Cazalla de la Sierra", Altitud_Metros: 550, Latitud: "Norte", Grado_La: 37, Minuto_La: 55, Segundo_La: 35, Longitudo: "Oeste", Grado_Lo: 5, Minuto_Lo: 46, Segundo_Lo: 11, Predicción: "Tormenta", Probabilidad_En_TantoPorciento: 100, TemperaturaMinima: 7, TemperaturaMaxima: 14, UltimaActualización: "22-11-2020", FechaPredicción: "25-11-2020"}, 
    {id: 4, Municipio: "Écija", Estacion: "Écija", Altitud_Metros: 130, Latitud: "Norte", Grado_La: 37, Minuto_La: 30, Segundo_La: 58, Longitudo: "Oeste", Grado_Lo: 5, Minuto_Lo: 5, Segundo_Lo: 6, Predicción: "Lluvia", Probabilidad_En_TantoPorciento: 20, TemperaturaMinima: 12, TemperaturaMaxima: 19, UltimaActualización: "22-11-2020", FechaPredicción: "25-11-2020"},
    {id: 5, Municipio: "Fuentes de Andalucía", Estacion: "Fuentes de Andalucía", Altitud_Metros: 165, Latitud: "Norte", Grado_La: 37, Minuto_La: 29, Segundo_La: 50, Longitudo: "Oeste", Grado_Lo: 5, Minuto_Lo: 25, Segundo_Lo: 59, Predicción: "Lluvia", Probabilidad_En_TantoPorciento: 100, TemperaturaMinima: 12, TemperaturaMaxima: 18, UltimaActualización: "22-11-2020", FechaPredicción: "25-11-2020"},
    {id: 6, Municipio: "Guadalcanal", Estacion: "Guadalcanal", Altitud_Metros: 720, Latitud: "Norte", Grado_La: 38, Minuto_La: 5, Segundo_La: 58, Longitudo: "Oeste", Grado_Lo: 5, Minuto_Lo: 49, Segundo_Lo: 9, Predicción: "Tormenta", Probabilidad_En_TantoPorciento: 100, TemperaturaMinima: 10, TemperaturaMaxima: 13, UltimaActualización: "22-11-2020", FechaPredicción: "25-11-2020"},
    {id: 7, Municipio: "La Puebla de los Infantes", Estacion: "La Puebla de los Infantes", Altitud_Metros: 200, Latitud: "Norte", Grado_La: 37, Minuto_La: 47, Segundo_La: 12, Longitudo: "Oeste", Grado_Lo: 5, Minuto_Lo: 22, Segundo_Lo: 16, Predicción: "Tormenta", Probabilidad_En_TantoPorciento: 100, TemperaturaMinima: 8, TemperaturaMaxima: 15, UltimaActualización: "22-11-2020", FechaPredicción: "25-11-2020"},
    {id: 8, Municipio: "La Roda de Andalucía", Estacion: "La Roda de Andalucía", Altitud_Metros: 410, Latitud: "Norte", Grado_La: 37, Minuto_La: 11, Segundo_La: 40, Longitudo: "Oeste", Grado_Lo: 4, Minuto_Lo: 46, Segundo_Lo: 12, Predicción: "Lluvia", Probabilidad_En_TantoPorciento: 100, TemperaturaMinima: 10, TemperaturaMaxima: 17, UltimaActualización: "22-11-2020", FechaPredicción: "25-11-2020"},
    {id: 9, Municipio: "Las Cabezas de San Juan", Estacion: "Las Cabezas de San Juan",Altitud_Metros: 105, Latitud: "Norte", Grado_La: 36, Minuto_La: 57, Segundo_La: 12, Longitudo: "Oeste", Grado_Lo: 5,Minuto_Lo: 50, Segundo_Lo: 48, Predicción: "Lluvia", Probabilidad_En_TantoPorciento: 100, TemperaturaMinima: 13, TemperaturaMaxima: 18, UltimaActualización: "22-11-2020", FechaPredicción: "25-11-2020"},
    {id: 10, Municipio: "Lora de Estepa", Estacion: "Lora de Estepa", Altitud_Metros: 105, Latitud: "Norte", Grado_La: 37, Minuto_La: 16, Segundo_La: 13, Longitudo: "Oeste", Grado_Lo: 4, Minuto_Lo: 49, Segundo_Lo: 37, Predicción: "Lluvia", Probabilidad_En_TantoPorciento: 100, TemperaturaMinima: 12, TemperaturaMaxima: 16, UltimaActualización: "22-11-2020", FechaPredicción: "25-11-2020"},
    {id: 11, Municipio: "Morrón de la Frontera", Estacion: "Morrón de la Frontera", Altitud_Metros: 87, Latitud: "Norte", Grado_La: 37, Minuto_La: 9, Segundo_La: 52, Longitudo: "Oeste", Grado_Lo: 5, Minuto_Lo: 36, Segundo_Lo: 41, Predicción: "Lluvia", Probabilidad_En_TantoPorciento: 100, TemperaturaMinima: 13, TemperaturaMaxima: 18, UltimaActualización: "22-11-2020", FechaPredicción: "25-11-2020"},
    {id: 12, Municipio: "Osuna", Estacion: "Osuna", Altitud_Metros: 255, Latitud: "Norte", Grado_La: 37, Minuto_La: 14,  Segundo_La:36,  Longitudo: "Oeste",  Grado_Lo: 5, Minuto_Lo: 6,  Segundo_Lo: 45,  Predicción: "Llovizna", Probabilidad_En_TantoPorciento: 100, TemperaturaMinima: 14, TemperaturaMaxima: 18, UltimaActualización: "22-11-2020", FechaPredicción: "25-11-2020"},
    {id: 13, Municipio: "Sevilla Capital", Estacion: "Sevilla Tablada", Altitud_Metros: 9, Latitud: "Norte", Grado_La: 37, Minuto_La: 21, Segundo_La: 51, Longitudo: "Oeste", Grado_Lo: 6, Minuto_Lo: 0, Segundo_Lo: 21, Predicción: "Lluvia", Probabilidad_En_TantoPorciento: 100, TemperaturaMinima: 12, TemperaturaMaxima: 18, UltimaActualización: "22-11-2020", FechaPredicción: "25-11-2020"},
    {id: 14, Municipio: "Sevilla Capital", Estacion: "Sevilla Aeropuerto", Altitud_Metros: 34, Latitud: "Norte", Grado_La: 37, Minuto_La: 25, Segundo_La: 0, Longitudo: "Oeste", Grado_Lo: 5, Minuto_Lo: 52, Segundo_Lo: 45, Predicción: "Lluvia", Probabilidad_En_TantoPorciento: 100, TemperaturaMinima: 12, TemperaturaMaxima: 18, UltimaActualización: "22-11-2020", FechaPredicción: "25-11-2020"},
    ])
db.sevilla.insertOne(
   {id: 15,
    Municipio: "Sevilla Capital", 
   Estacion: "Torreblanca", 
   Altitud_Metros: 56, 
   Latitud: "Norte", 
   Grado_La: 37, 
   Minuto_La: 25, 
   Segundo_La: 0, 
   Longitudo: "Oeste", 
   Grado_Lo: 5, 
   Minuto_Lo: 52, 
   Segundo_Lo: 45, 
   Predicción: "Nublado", 
   Probabilidad_En_TantoPorciento: 56, 
   TemperaturaMinima: 13, 
   TemperaturaMaxima: 18,
   UltimaActualización: "22-11-2020",
   FechaPredicción: "25-11-2020",}
)